# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: facf296efe17971ec577a473b46df94385ed19313b3fb773eb848e829346156358953b8a85d53a996e088822c887819339493e8de3b599b689df4872d642e79d

test:
  secret_key_base: 16497c85f24e43ee07c4aefc9116a642427dd13a5aeb9bcca73313458c18fad57757826b91e62d2b8805fd87b2aef10606c45ace090e00105c03a99092927d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
